name: Build

on: [push, pull_request]
jobs:
  build-macos-catalina:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: brew install open-mpi
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
          mkdir Build
          cd Build
          cmake .. 
          make -j3
      - name: Create installer
        shell: bash
        run: |
          cd Build/svSolver-build
          cmake . -DSV_ENABLE_DISTRIBUTION=ON
          make
          cpack
          cp svsolver*.pkg ../../svSolver-macOS-Catalina.pkg
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS Catalina Installer
          path: svSolver-macOS-Catalina.pkg
          if-no-files-found: error
      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: svSolver-macOS-Catalina.pkg
          asset_name: svSolver-${{github.ref_name}}-macOS-Catalina.pkg
          tag: ${{ github.ref }}
